### ISSUE TITLE
It is possible to create a project without a valid project template

### ISSUE THREAD

**Issue by fungiboletus** [DataCloud-project/SIM-PIPE#130]
- [ ] Template is missing
 - [ ] Template is invalid (wrong syntax or wrong logic)

**Comment by goranbs** [comment]
Can we have a template validation - to display that the workflow template is invalid or missing, in stead of making it impossible to create a project without a valid workflow template, so that a valid template can be added later?

**Comment by goranbs** [comment]
This is described here: #136 

Closing this due to duplicates.
