### ISSUE TITLE
[Feature request]: Automatic line returns in the log view

### ISSUE THREAD

**Issue by fungiboletus** [DataCloud-project/SIM-PIPE#53]
### Is your feature request related to a problem? Please describe

The log view doesn't handle end of lines.

### Describe the solution you'd like

`white-space: pre-wrap` would do.

### Describe alternatives you've considered

NA

**Comment by goranbs** [comment]
Resolved: https://github.com/DataCloud-project/SIM-PIPE/blob/625af7402dde2dd230a93079156937934322fdc1/frontend/src/routes/projects/%5Bproject_id%5D/%5Bdry_run%5D/%5Bresource%5D/%2Bpage.svelte#L574
