### ISSUE TITLE
[Feature request]: Implement file managements

### ISSUE THREAD

**Issue by fungiboletus** [DataCloud-project/SIM-PIPE#71]
### Describe the solution you'd like

Add front-end button to use previously used files for input to pipeline

**Comment by goranbs** [comment]
Linked to issue [#141](https://github.com/DataCloud-project/SIM-PIPE/issues/141) in witch we plan to implement file-management for input artifacts.

**Comment by goranbs** [comment]
The following CRUD operations has been resolved in #141 :
- [v] create new 
- [] delete buckets (should be easy to implement)
- [v] upload artifacts
- [v] delete artifacts
- [] download artifacts (needs more elaborate work)

Closing this.
