### ISSUE TITLE
Test BC pipelines

### ISSUE THREAD

**Issue by elvesater** [DataCloud-project/SIM-PIPE#74]
Import existing BC pipelines from DEF-PIPE and try to run them in SIM-PIPE:
- [ ] JOT
- [x] MOG
- [x] TLU (used as demonstrator pipeline for the informal review)
- [ ] CER
- [ ] BOS

**Comment by AleenaThomas-gh** [comment]
Except for MOG and Bosch, the other business case pipelines were tested in an earlier version of SIM-PIPE.

**Comment by goranbs** [comment]
datacloud project finished. closing.
