### ISSUE TITLE
Switch from monochromatic to colour in logs display

### ISSUE THREAD

**Issue by fungiboletus** [DataCloud-project/SIM-PIPE#88]

**Comment by goranbs** [comment]
Currently using skeleton.dev code blocks with BASH formatting to display logs ([https://www.skeleton.dev/utilities/codeblocks](https://www.skeleton.dev/utilities/codeblocks)).

Is there still a need for (or just a nice-to-have) changing the colors in logs?

**Comment by goranbs** [comment]
Can we close this issue?

**Comment by fungiboletus** [comment]
I think this issue is more about [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code) and colours, than syntax highlighting. It's a nice to have, not high priority, but it could also be a low hanging fruit that looks cool.
